<ul>
 <li>1.4.0 - December 2024
    <p>- Added an option to clear all errors</p>
    <p>- Added an option to export all logs</p>
    <p>- Added new sub permissions</p>
  </li>
  <li>1.3.0 - July 2024
    <p>- Global Error Handler Initialization</p>
    <p>- Static Variable for Single Initialization</p>
    <p>- Remove Redundant Initialization</p>
    <p>- Autoloading and Smarty Integration</p>
    <p>- Improved Error Handling Logic</p>
  </li>
  <li>1.2.0 - July 2024
    <p>- Made the module a registeredEvent</p>
    <p>- Created a testing platform on {LogWatch} default action</p>
    <p>- Made E_ALL the default selection</p>
  </li>
  <li>1.0.0 - June 2024
    <p>Initial Release</p>
  </li>
</ul>
